NCP: 3.0.1 upgrade to stemcell 621.76 fails
```
bosh -d ncp deploy ncp.yml
Using environment 'bosh-vsphere.nono.io' as user 'admin'

Using deployment 'ncp'

  instance_groups:
  - name: ncp
-   stemcell: 621.75
+   stemcell: 621.76

Continue? [yN]: y

Task 16577

Task 16577 | 19:40:50 | Preparing deployment: Preparing deployment (00:00:04)
Task 16577 | 19:40:54 | Preparing deployment: Rendering templates (00:00:00)
Task 16577 | 19:40:54 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 16577 | 19:40:54 | Compiling packages: openvswitch/755dded7e07d7502bf72bd204d3b22b52b9fc28b (00:02:33)
                     L Error: Action Failed get_task: Task a638a729-37b3-41e1-7749-1a3ccf064958 result: Compiling package openvswitch: Running packaging script: Running packaging script: Command exited with 2; Truncated stdout: PYTHONPATH=./python":"$PYTHONPATH PYTHONDONTWRITEBYTECODE=yes /var/vcap/packages/nsx-python27/bin/python2 ./ovsdb/ovsdb-idlc.in c-idl-header vtep/vtep-idl.ovsidl > vtep/vtep-idl.h.tmp && mv vtep/vtep-idl.h.tmp vtep/vtep-idl.h
...
/var/vcap/data/compile/openvswitch/openvswitch-2.12.1.16098734/datapath/linux/geneve.c: In function 'geneve_get_v6_dst':
/var/vcap/data/compile/openvswitch/openvswitch-2.12.1.16098734/datapath/linux/geneve.c:966:15: error: 'const struct ipv6_stub' has no member named 'ipv6_dst_lookup'
  if (ipv6_stub->ipv6_dst_lookup(geneve->net, gs6->sock->sk, &dst, fl6)) {
               ^
make[5]: *** [/var/vcap/data/compile/openvswitch/openvswitch-2.12.1.16098734/datapath/linux/geneve.o] Error 1
make[4]: *** [_module_/var/vcap/data/compile/openvswitch/openvswitch-2.12.1.16098734/datapath/linux] Error 2
make[3]: *** [default] Error 2
make[2]: *** [all-recursive] Error 1
```