BOSH vSphere has AWS CPI installed
- `vsphere.yml` manifest operations file has necessary AWS CPI
  properties (releases, jobs, properties)
- `vsphere.sh` passes in correct AWS values (e.g. region)
- `vsphere.yml` no longer shrinks disk 32G → 20G; I have
  **so much** disk. I mean, really. Unbelievable amounts.

fixes:
```
Parsing release set manifest '/Users/cunnie/workspace/bosh-deployment/bosh.yml':
  Evaluating manifest:
    - Expected to find variables:
        - default_key_name
        - default_security_groups
        - region
```
```
Error: Failed to run cpi: '/var/vcap/jobs/aws_cpi/bin/cpi' is not executable
```