Docker file has appropriate pre-reqs
See this: https://bosh.io/docs/cli-env-deps.html

Needed to go back to Fedora 25 to get 1.0.x version of
openssl; CPI wouldn't build with newer ones.

fixes:
```
Deploying:
  Deleting existing instance 'unknown/0':
    Checking existence of vm for instance 'unknown/0':
      Checking existence of VM 'i-048fb77f8af5a4ab4':
        CPI 'has_vm' method responded with error: CmdError{"type":"Unknown","message":"undefined method `set_api' for #\u003cClass:0x0055fd4c1a7738\u003e","ok_to_retry":false}
```
fixes: https://github.com/openssl/openssl/issues/2239
```
 error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
```