🐞 .envrc accommodates yq versions 3 & 4
My work environments need `yq` version 3, which has a completely
different syntax than version 4, so with this fix the `.envrc` will work
properly on my work machines.

Fixes:
```
Error: unknown command "e" for "yq"
```